### ISSUE TITLE
Should support tencent unpacker

### ISSUE THREAD

**Issue by strazzere** [strazzere/android-unpacker#10]
Easily identified by the class;

com/tencent/StubShell/ProxyShell

Also usually included
libmain.so
libshell.so

Lots of references to tx_shell.

Appears to support ART as well as Dalvik.

**Comment by GSharma789** [comment]
hi dev , unpacker not detecting tencent bugly packer

**Comment by srimodi** [comment]
￼

Networkcapture

**Comment by srimodi** [comment]
[Networkcapture](https://play.google.com/store/apps/details?id=com.minhui.networkcapture)

**Comment by GSharma789** [comment]
Pro version of this app has 
1: libshellx-2.9.0.2.so
2: libshella-2.9.0.2.so
3. libBugly.so
4. mixz.dex
5. mix.dex
And
Hash Of Apk Is 
MD5  = B4E5C6AA974026291C04FCE95687F2BF
SHA1= 8424B792F2BBEE13EBE59F6083D9FD4AE0B755D5

Hope there is support for tencent bugly . Thanks

**Comment by GSharma789** [comment]
@strazzere please have look at it

**Comment by strazzere** [comment]
Pull requests are welcome, this packer isn't too hard to defeat if you just modify the code a bit

**Comment by GSharma789** [comment]
you are great programmer sir not we are . don't know where to make change and what need to change . please explain a little

**Comment by cryptax** [comment]
@GSharma789 this might help you: https://www.fortinet.com/blog/threat-research/unmasking-android-malware-a-deep-dive-into-a-new-rootnik-variant-part-i.html

**Comment by GSharma789** [comment]
@cryptax thank you . But i already unpack it with frida by hook dexfileopenmemory . I asked here because this awesome unpacker not worked properly

**Comment by cryptax** [comment]
Oh interesting! Can you share your frida hook? That's another way to do it
indeed.

**Comment by GSharma789** [comment]
hi @cryptax have a look here https://github.com/dstmath/frida-unpack

**Comment by strazzere** [comment]
Going to close this - ijiami is pretty simple to unpack and the above links can help :)
