### ISSUE TITLE
Installation process unclear

### ISSUE THREAD

**Issue by muntaha14** [strazzere/android-unpacker#11]
Hi,

I need to use unpacker to analyse protected applications but the installation process is not clear. I read the readme file of "native-unpacker" but I am not clear what the prerequisite etc are. 

Its first step says, "Assumes ndk-build and $ANDROID_NDK_SYSROOT are properly set". Can you please elaborate it? What does it mean to be "set"? 
Also step "Push to the device", is it the android device/emulator?

Can we use this tool on emulators or just devices? And is proper root and busybox required?

Can you please explain the setup in simple words so that people who do not have NDK experience can also benefit from this tool.

Thanks,

**Comment by strazzere** [comment]
Assuming I have find some time this week, I'll try to link the necessary pre-requisites and link to the Android NDK documentation.

**Comment by berryman13** [comment]
I agree, is there any way I can help strazz? This needs docs/wiki

**Comment by strazzere** [comment]
Feel free to try and do it if you'd like. I might end up having time this weekend, though this really isn't a priority to me...

The TLDR version of it is already in the repo (have NDK, compile, have root).

**Comment by berryman13** [comment]
I get the TL;DR, but I think I am under the category most other people are as well: can build it and get it working, doesn't know any way to apply it. I can expand upon building and NDK/root, but examples probably need to come from your spare time.

**Comment by UzminTid** [comment]
(I hope my advice doesn't seem to be too late 4 you or others)

(1). Install NDK 
      1.Download NDK(bin) 
      2.Put it to somewhere you like to put 
      3.Install it (You can find "how to install it" by using Google)
(2).Make (IMPORTANT:I used the way DIFFERENT from the way README.md told me because i also cant understand it as a  beginner )

      (So we have native-unpacker and android-ndk-XXXX)(XXXX is ndk's ver)
      1.Try to get into android-ndk-XXXX (floder)   (You can ask Google if you don't know how to do it)
      2.Well i see someone called " ndk-build" maybe it can help us to build this program  
      3.Let's try to launch it in Terminal
      4.It told us :
              Android NDK: Could not find application project directory !
      5.What is this mean? Let’s Google it !
      6.Mr.Google told us to change our command into " ndk-build NDK_PROJECT_PATH=XXXXXXX"(your project 's dir)
      7.Well....Another error occurred .it said:
              Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: /home/tiger/android-unpacker/native-unpacker/jni/Android.mk    
      8.Pay attention to the dir it said ,did you find "/jni/" was added?

**Comment by strazzere** [comment]
This issue should now be resolved, thanks all.
