### ISSUE TITLE
Where to find gdb binary

### ISSUE THREAD

**Issue by gaurav9991** [strazzere/android-unpacker#14]
Hi,

It is unclear where to find **gdb binary** to push to "/data/local/tmp/".

I am using **android emulator** and I had no issues in building and using "native-unpacker" but I am unable test **"gdb-scripts"** because I can't find gdb binary to use.

Thanks.

**Comment by strazzere** [comment]
It really depends on what architecture (for you device/emu) you're going to be using, though I compiled mine from source. This looks like something that might be of assistance to you;
https://github.com/darchons/android-gdb
