### ISSUE TITLE
Fix Android.mk to produce PIE executables

### ISSUE THREAD

**Issue by balidani** [strazzere/android-unpacker#20]
Hi!

I couldn't get the native unpacker to work, it gave me the following error:

    error: only position independent executables (PIE) are supported.

Is this a known issue? After some googling I found the fix. These lines need to be added to `Android.mk`:

    APP_PLATFORM := android-16
    LOCAL_CFLAGS += -pie -fPIE
    LOCAL_LDFLAGS += -pie -fPIE

This will only work on Android 4.1+.

Cheers!

**Comment by strazzere** [comment]
Thanks for pointing this out, I had a fix on my local branch that I apparently never pushed. This should work now.
