### ISSUE TITLE
DexProtector

### ISSUE THREAD

**Issue by aleks921** [strazzere/android-unpacker#21]
My android tools packed with DexProtector.
How unpack this protector ? Can you add unpack this protector in your tool ?

**Comment by geo2550** [comment]
What maybe

George Whitehill

**Comment by aleks921** [comment]
How unpack this protector ?  Help me please.

**Comment by strazzere** [comment]
Follow the directions in the README. This however is a relatively old project, so it depends on which version of dexprotector was used for the APK in question. Feel free to post it if you'd like - however this isn't really an "issue" with the project.

**Comment by aleks921** [comment]
How know version of dexprotector on this apk ?

**Comment by aleks921** [comment]
It http://rgho.st/8Bqs7JDxG  apk with DexProtect. Do you can say me about version ?

**Comment by strazzere** [comment]
"My android tools packed with DexProtector."

If it's yours, then I'd assume you know what version you used ;)

**Comment by aleks921** [comment]
It isn't my project. Packed not me. Can you know version ? How find version in this protector ?

**Comment by strazzere** [comment]
Unsure, it's newer than I've seen (Everything encrypted and stripped) I'd suggest trying to use the LKM method described by the `antiunlink` module;

https://github.com/strazzere/android-lkms

**Comment by aleks921** [comment]
How install LKM method ? On windows or linux or android this tools need install ? Nedd root on android ?

**Comment by aleks921** [comment]
How install your tools https://github.com/strazzere/android-unpacker on android ?
I download package on android and in directory your project do comand: make, but android write that "make not found". How install on android this ? Help me please.

**Comment by CalebFenton** [comment]
Why are you trying to install this on Android? You'll find it's much easier to install on Linux or Mac. You'll need build tools and a working NDK environment.

**Comment by strazzere** [comment]
Yes, what @CalebFenton started discussing. Sadly, I'm not going to have enough time to attempt to do support for setting up the NDK, compiling files, etc. This is a highly technical project which has a rather high bar set for using the tools.

I'll also note that it's very likely that the APK you're referencing may not be unpacked properly by this project (thus why I suggest using the android-lkm project). You'll likely have more success getting this unpacked by finding (or likely by hiring) a technical person to do this work for you.

**Comment by aleks921** [comment]
Ok, I understand that on Linux, but after install need push compiled tools on android or stay on linux ?
I dont understant this comand in readme adb shell ./data/local/tmp/kisskiss com.package.name.to.unpack
This ./data/local/tmp/kisskiss adress in Linux or nedd compiled tools push in android in ./data/local/tmp ?

**Comment by strazzere** [comment]
`kisskiss` is the binary which is cross compiled on your host system. This gets pushed (uploaded) to the device and run on the device via the command `adb shell ./data/local/tmp/kisskiss com.package.name.to.unpack`

**Comment by aleks921** [comment]
Thank you for your answer.
I want ask yet question about NDK, Android NDK need install on Linux only for build and install kisskiss tool ? After upload kisskiss on android virtual device NDK is not required yet in my system Linux ?
Can I after compile and upload kisskiss on android do comand "adb shell ./data/local/tmp/kisskiss com.package.name.to.unpack" on Windows system without NDK ?

**Comment by strazzere** [comment]
The Android NDK is required to compile the code, as stated in the README;

https://github.com/strazzere/android-unpacker/blob/master/native-unpacker/README.md

You could likely compile this on Linux or Windows, personally I did this on OSX. If compiling on Windows, you likely would need to modify the make file - or potentially use cygwin or something. Honestly, I'm not sure. Once the binary is compiled, you wouldn't need the NDK anymore - unless you need to modify the code (and recompile, etc).

After you have the binary compiled, it doesn't matter what system your using, as long as you can use `adb` to interact with the device and already pushed `kisskiss` to the device.

**Comment by aleks921** [comment]
Thank you. I will compile on Linux. I use emulator Genimotion. Can you say about SELinux, in this emulator this disabled or not ? And how off SELinux if enabled in this emulator.

**Comment by strazzere** [comment]
I don't know, you'll likely need to modify the make file to create a x86 binary for Genimotion. I can't speak towards what level of SELinux they have though.

**Comment by aleks921** [comment]
The original Make file for ARM virtual devices only ? If i do not modify make, so the binaries will only run on ARM devices?

**Comment by strazzere** [comment]
Yes;

https://github.com/strazzere/android-unpacker/blob/master/native-unpacker/Makefile#L1

I'm not going to reply to this thread anymore. You need to figure out the rest of the steps yourself, I'm not going to do this work for you.

**Comment by aleks921** [comment]
I understand, thank you for your answer.

**Comment by aliheidari020** [comment]
Plz help me
I run 
adb shell ./data/local/tmp/kisskiss com.package.name.to.unpack
Will not run properly
https://s11.postimg.org/l9qqlzfsj/Untitled.png

**Comment by strazzere** [comment]
1 - Please open a new issue.
2 - It would appear you've compiled it (maybe correctly?) - though you're literally trying to run it against `com.package.name.to.unpack` which does not likely exist.
3 - You probably just need to `chmod` the binary, but I don't know...
