### ISSUE TITLE
Pread errors for bangcle packed samples (not new bangcle version)

### ISSUE THREAD

**Issue by amanaksu** [strazzere/android-unpacker#23]
While it is trying to test the android-unpacker when tested in the following circumstances: a memory dump error has occurred.
Perhaps there may be a permissions problem, or AVD version?
Do you know why?

The sample is a malware collected in February 2015.
Aside from January 2015, two bangcle are the same error.

< Test Environment >
- Base OS : Kali Linux
- AVD 1. Android 4.4.2 (API 19) Google API ARM
- AVD 2. Android 5.0.1 (API 21) Google API ARM

< Error Log >
[_] Android Dalvik Unpacker/Unprotector - strazz@gmail.com
 [+] Hunting for com.zhiqupk.root
 [+] 2076 is service pid
 [+] 2171 is clone pid
 [+] Attempting to detect packer/protector...
  [_] Nothing special found, assuming Bangcle...
 [+] Unpacked odex found in memory!
 [+] Attempting to dump memory region 0xbe572000 to 0xbe572000
 [!] pread seems to have failed!
 [!] An issue occurred trying to dump the memory to a file!

< Test Sample >
https://www.virustotal.com/en/file/bf6c13323521eb064a116d0322351ff6a24fb1554e5608c8e94065e0cf4c6293/analysis/

**Comment by strazzere** [comment]
This should be fixed now - it was related to `off_t` wrapping since `0xbe572000` is too large. Switched to using `pread64`.
