### ISSUE TITLE
Plz help me for unpack qihoo

### ISSUE THREAD

**Issue by aliheidari020** [strazzere/android-unpacker#24]
Plz help me
I run 
adb shell ./data/local/tmp/kisskiss com.package.name.to.unpack
Will not run properly
https://s11.postimg.org/l9qqlzfsj/Untitled.png

**Comment by strazzere** [comment]
You'll need to post the binary, however like I said in the other issue. It would appear you're not actually setting the executable `kisskiss` to be executable. Also, `com.package.name.to.unpack` should be the actual package name you want to unpack...
