### ISSUE TITLE
Plz help me

### ISSUE THREAD

**Issue by aliheidari020** [strazzere/android-unpacker#25]
Hi
something unexpected happened, new version of packer/protectors? or it wasn't packed/protected!
https://s11.postimg.org/cuo4v24b7/Untitled1.png

**Comment by strazzere** [comment]
You'll need to share the hash or the file at a minimum...

**Comment by obnauticus** [comment]
Same issue here. I've attached the file.

Please see APK located here:
www.apkmonk.com/app/cn.ninebot.ninebot/

**Comment by strazzere** [comment]
Closing old issue that lacks context / details.
