### ISSUE TITLE
Please someone unpack this file and Make instructional video for me

### ISSUE THREAD

**Issue by aliheidari020** [strazzere/android-unpacker#27]
https://ufile.io/c7915
hi please someone download this file https://ufile.io/c7915 and unpack this file and create Training video for me 
I do not know unpack 
I need my instructional video for unpack 
plz help me My English is bad.
thanks

**Comment by CalebFenton** [comment]
I don't mean to sound rude but I will say this simply: you are asking a lot from people. You should try and figure it out yourself or at least show you are trying to learn. No one will help you if you just ask for free stuff. Why should they?

For reference, this is the hash:
https://www.virustotal.com/en/file/beff5c343014ec27bccaced7b84cda51517dad5ff97350b3f6bd3fc687d79bd3/analysis/1478561214/
