### ISSUE TITLE
An issue occured when unpacking qihoo apk

### ISSUE THREAD

**Issue by neosarchizo** [strazzere/android-unpacker#28]
I compiled kisskiss successfully. But when I ran kisskiss, I got following error message.

![An issue occurred trying to dump the memory to a file!](http://i.imgur.com/xCWvAoa.png)

I want to know what is problem and how to view error log.

**Comment by strazzere** [comment]
Can you provide the sha1 or upload the file you're attempting to unpack?

Seems like it may have reprotected the memory region it's attempting to dump.

**Comment by neosarchizo** [comment]
Following is a link of the application.

https://play.google.com/store/apps/details?id=com.ore.yorkfeng.comfortbase

**Comment by Jasi2169** [comment]
same issue on different app with same qihoo target

**Comment by vossim** [comment]
I'm getting similar issues, also with a quhoo apk

**Comment by strazzere** [comment]
Please upload an application. If you're getting this error, you'll need up provide a hash, download link and the exact error.

Specifically if you're saying "it's a quhoo apk" (which isn't actually a thing, I believe you mean qihoo) look to see if anything is being detected. If not, much like the example above, this means it's likely a new version and you need to provide the above information in a new issue as a feature request.

I'd also suggest running APKiD on it to ensure you know which protection it is being detected as.

**Comment by neosarchizo** [comment]
@strazzere The app is [Comfort Base Remote](https://play.google.com/store/apps/details?id=com.ore.yorkfeng.comfortbase).
