### ISSUE TITLE
Should be able to unpack secneo

### ISSUE THREAD

**Issue by strazzere** [strazzere/android-unpacker#3]
@goodhacker mentioned the following;

<<
root@ubuntu:~/Desktop/native-unpacker# adb shell /data/local/tmp/kisskiss com.MobileTicket
[] Android Dalvik Unpacker/Unprotector - diff@lookout.com
[+] Hunting for com.MobileTicket
[+] 695 is service pid
[+] 737 is clone pid
[+] Attempting to detect packer/protector...
[] Nothing special found, assuming Bangcle...
[!] Something unexpected happened, new version of packer/protectors? Or it wasn't packed/protected!

Sample I was able to track down appears to be using "secneo" which is supposedly the commercial version of Bangcle. Further investigation needed.

**Comment by CunningLogic** [comment]
hinter,

I've been waiting for months, I'm still not in jail. When will this happen?

**Comment by strazzere** [comment]
This appears to have been working for a long time :)

**Comment by therealx** [comment]
So wait, sorry to be safe, but reversing secneo works using the bangcycle code?  I can add detection to the main script if so

**Comment by therealx** [comment]
Daft,. Not safe

**Comment by strazzere** [comment]
This specific version of secneo works to be unpacked.
