### ISSUE TITLE
Is there a precompiled version or some proper instructions ??

### ISSUE THREAD

**Issue by parind** [strazzere/android-unpacker#35]
I am using Android Studio with NDK Installed but there seems to be a problem, Android Studio wont detect what type of project its using because theres no file like build.gradle indicating something. So its unclear for me too to go on with the project. If someone would help, it would be much appreciated.

**Comment by strazzere** [comment]
There is no precompiled version of this. The reason Android Studio doesn't detect anything is that this is not an Android Studio based project.

If you follow the instructions here;
https://github.com/strazzere/android-unpacker/blob/master/native-unpacker/README.md

It should work - it only requires minor modifications to the `Android.mk` file
https://github.com/strazzere/android-unpacker/blob/master/native-unpacker/Android.mk

**Comment by strazzere** [comment]
Whoops, I meant the `Makefile`;
https://github.com/strazzere/android-unpacker/blob/master/native-unpacker/Makefile

This does a simple `which ndk-build` and will fail if the Android NDK isn't properly on your `PATH`.

**Comment by parind** [comment]
I am still unable to compile. Goes on endless errors like Path Not Found, Project Not Found, etc. God Its so messed up. Can this be compiled with gcc and if yes please can you post all the command parameters required like toolchain to be used or something else.

**Comment by strazzere** [comment]
Hopefully, it works -- it hasn't been updated in a while, though the fundamentals still work on many things with just some minor tweaks.

**Comment by GSharma789** [comment]
@parind please tell me step to compile it properly . I can not find your email on your profile else i could email you , my email is govindsharma111998@gmail.com , you may send me steps on email or here . Thanks in advance
