### ISSUE TITLE
UnpackError

### ISSUE THREAD

**Issue by xitanaf** [strazzere/android-unpacker#37]
Hello
Please, where is the error?
http://boris.fanatix.sk/dji.png

app: https://www.apkmirror.com/apk/dji-technology-co-ltd/dji-go-4/dji-go-4-4-1-15-release/dji-go-4-for-drones-since-p4-4-1-15-2-android-apk-download/

thank you for any advice

**Comment by strazzere** [comment]
This is likely because the device has selinux running and turned on. Try deactivating it or using an emulator with it disabled.
