### ISSUE TITLE
Secneo apkwrapper support

### ISSUE THREAD

**Issue by h3ku** [strazzere/android-unpacker#39]
Hi, 
I'm trying to reverse engineer the following application.
https://play.google.com/store/apps/details?id=cn.ninebot.ninebot

Based on the content of the main dex file it looks like that use secneo apkwrapper.

It looks like contains anti-debug tricks and other things similar to APKProtect.

Any advice?

**Comment by strazzere** [comment]
According to https://github.com/strazzere/android-unpacker/issues/38 this should be solved with the latest updates.

Can you confirm?

**Comment by h3ku** [comment]
Nop, I try with the latest master from GitHub and I got the following result.
![image](https://user-images.githubusercontent.com/5603877/36246757-8d193dda-1231-11e8-8f2d-0a69b96d2274.png)

I attach the output of APKiD too.
![image](https://user-images.githubusercontent.com/5603877/36246783-a4d79d2c-1231-11e8-8d9a-ce26d76a6678.png)

**Comment by strazzere** [comment]
Ah I may have been mixing up previously fixed issues. I do know at least older versions of that specific package where unpack-able.

Can you please provide a hash and/or upload the file you're attempting to work on? From there we can actually test/working on the issue.

**Comment by h3ku** [comment]
This is the APK
https://drive.google.com/file/d/1wTxR6G9kZRU5V7gF-4L-MTdgVRqQM_41/view

I was trying to do it on a Nexus 5X, I can't remember the exact android version but I can check it tomorrow.

**Comment by strazzere** [comment]
Ah, yes - this is the new enterprise version of secneo that no one was publicly released a free unpacker for.

**Comment by Gabrieldaboss65** [comment]
@h3ku hey i want to reverse the exact same app. did you ever figure something out?

**Comment by strazzere** [comment]
This is the enterprise secneo version.

There are, currently, no public postings online on how to reverse this
fully.

If you're interested in contract work to solve this issue - please contact
me (or ask around).

This will never be solved within the scope of this project both for
technical and legal reasons.

**Comment by strazzere** [comment]
Going to close this issue as it will not be addressed publicly on this repo. Reach out directly (privately) if there is any need for this.

**Comment by GSharma789** [comment]
@hk3u did u tried frida ? . I managed to dump the dex with frida

**Comment by MAVProxyUser** [comment]
https://github.com/quarkslab/dxfx

**Comment by rebasecase** [comment]
@MAVProxyUser better if you provided context to its relevancy  rather than linking a repository with no additional information

**Comment by MAVProxyUser** [comment]
> [@MAVProxyUser](https://github.com/MAVProxyUser) better if you provided context to its relevancy rather than linking a repository with no additional information

lol wut? Bro go to the repository and figure out the context yourself? It isn't THHHHHHHAT hard. Literally in the README.md "This tool provides a way to statically unpack the bytecode of the DJI Pilot Android app, which uses a modified version of the SecNeo packer" can you *guess the context? or no? Like come on fam... the effort it too you to type that reply out, you could have shook out the context, and realized it was all there in the first place. 

Thanks for the pro tip just the same.
