### ISSUE TITLE
Unable to unpack a Qihoo app

### ISSUE THREAD

**Issue by kurocygnus** [strazzere/android-unpacker#43]
[*] Android Dalvik Unpacker/Unprotector - <diff@lookout.com>
 [+] Hunting for com.brazil.vod
 [+] 1949 is service pid
 [+] 2003 is clone pid
 [+] Attempting to detect packer/protector...
  [*] Nothing special found, assuming Bangcle...
 [+] Unpacked odex found in memory!
 [+] Attempting to dump memory region 0xb7781000 to 0xb7782000
 [!] pread seems to have failed!
 [!] An issue occured trying to dump the memory to a file!

I'm using Nox Emulator to do this since I don't have a rooted device.

**Comment by strazzere** [comment]
Nox emulator? Can you provide a link for that?

Can you please also upload the file in question?

**Comment by strazzere** [comment]
I'd also suggest doing a `git pull` because it appears you're running some code that is minimally 3 years old;

https://github.com/strazzere/android-unpacker/commit/97ad55d700068c6b0f3880f3ee87414ee67f497a

**Comment by strazzere** [comment]
Ok, so, it does look fairly similar to issue #42 - however I won't close this issue until you can rerun the new code against it.

I do think that this is just, the same packer and will complain due to `mprotect` usage about i/o issues.

**Comment by strazzere** [comment]
Ok cool, seem to be the same issue as #42 -- it's likely do to `mprotect`. There are some suggestion in that issue on how to handle this, but for the time being I'm going to close this one since it's a duplicate.
