### ISSUE TITLE
How can I configure NDK path in Window?

### ISSUE THREAD

**Issue by camlhsegu** [strazzere/android-unpacker#45]
This is my Makefile:
    `build:
	ndk-build NDK_PROJECT_PATH=C:/Users/admin/AppData/Local/Android/sdk/ndk-bundle/build/ndk-build.cmd APP_BUILD_SCRIPT=./Android.mk`

Can you help me?

**Comment by strazzere** [comment]
This is really dependent on your environment. I suggest you Google the solution or ask in a dev channel where other folks use Windows. I personally don't compile any of this tooling on windows, but it should work if you know what to modify.
