### ISSUE TITLE
Need Precompiled version . From #35

### ISSUE THREAD

**Issue by GSharma789** [strazzere/android-unpacker#46]
Hi dev , i don't own a pc to compile the unpacker , if you or some great guys can upload a precompiled version that will be great. Only can use adb from friends pc . Thanks

**Comment by strazzere** [comment]
Sorry, I don't post precompiled code here as it is highly dependent on the use case / device / app. It will almost always be incorrect for who ever is downloading it.

You're welcome to request help in the slack channel and/or post a hash. Though this repo is not the proper place to ask for assistance unless the unpacker is explicitly not functional on that specific packer.
