### ISSUE TITLE
Nothing special found, hunting for all dex and odex magic bytes

### ISSUE THREAD

**Issue by weinixuehao** [strazzere/android-unpacker#51]
![image](https://user-images.githubusercontent.com/17869361/71163166-7fe70f80-2287-11ea-9dc1-95755007dc58.png)

**Comment by strazzere** [comment]
Whats the binary? Can you share it? Whats it's protected by?

Looks like the memory regions are protected and you'll need to modify it to unprotect them.

Though, hard to tell since there is no data in this ticket... And just an image...
