### ISSUE TITLE
unable to unpack 'Jiagu'

### ISSUE THREAD

**Issue by matrixboot** [strazzere/android-unpacker#54]
@strazzere 
I've tried using the native-unpacker on the following apk: [APK](http://www.brasil-tv.net/download)
 packer : Jiagu

![fail](https://user-images.githubusercontent.com/76606593/103145675-cda91a00-471c-11eb-83fd-6f1093f21a63.png)

Please help me

**Comment by strazzere** [comment]
This unpacker is relatively old and not meant to be a one size fits all
solution but just to show you how it could be done.

Feel free to read the other issue where people discuss how to unpack apks
like this, but do not post requests for unpacking.
