### ISSUE TITLE
Should support 'ijiami' packer/protector

### ISSUE THREAD

**Issue by strazzere** [strazzere/android-unpacker#6]
New sample packer found ITW which doesn't currently get unpacked properly. More details to follow.

**Comment by v14dislav** [comment]
Doesn't it support now?

**Comment by strazzere** [comment]
Hah, yes - it does last time I checked. Good notice on this old issue.

**Comment by v14dislav** [comment]
It doesn't work now :(

127|hammerhead:/data/local/tmp # ./kisskiss one.show.live                                                                                                                                                                                                                                
[*] Android Dalvik Unpacker/Unprotector - <strazz@gmail.com>
 [+] Hunting for one.show.live
 [+] 3310 is service pid
 [+] 4677 is clone pid
 [+] Attempting to detect packer/protector...
  [*] Nothing special found, hunting for all dex and odex magic bytes...
  [*] No packer found on clone_pid 4677, falling back to service_pid 3310
 [+] Attempting to detect packer/protector...
  [*] Nothing special found, hunting for all dex and odex magic bytes...
  [!] pread seems to have failed at 0x982c1000
 [!] Error peeking at memory : I/O error
  [!] pread seems to have failed at 0xb5048000
 [!] Error peeking at memory : I/O error
 [!] Something unexpected happened, new version of packer/protectors? Or it wasn't packed/protected!

**Comment by GSharma789** [comment]
@v14dislav can you upload one.show.live apk here ?

**Comment by v14dislav** [comment]
@GSharma789 
 
https://activity-download.xiubi.com/ apk is here. 
Ijiami uses dynamic code modifications, anti debugging tricks and many more. So frida-unpack doesn't work. Xposed with Fdex2 module gave me 3 .dex files but methods in classes are empty

**Comment by v14dislav** [comment]
@v14dislav it was on Android 6.0.2 , nexus 5
